version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: dummy_user
      MYSQL_PASSWORD: dummy_password
    ports:
      - "3306:3306"

