
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./volumes/readarr/data:/config
      - ./volumes/readarr/books:/books #optional
      - ./volumes/readarr/downloadclient-downloads:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped
