---
services:
  openvscode-server:
    image: lscr.io/linuxserver/openvscode-server:latest
    container_name: openvscode-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CONNECTION_TOKEN= #optional
      - CONNECTION_SECRET= #optional
      - SUDO_PASSWORD=shivajivayile #optional
      - SUDO_PASSWORD_HASH= #optional
    volumes:
      - ./vsc/config:/config
    ports:
      - 4003:3000
    restart: unless-stopped
