# guide: https://shahar-avigezer.github.io/blog/wiremock/
services:
  wiremock-wwe-server:
    image: wiremock/wiremock:2.32.0
    ports:
      - 3001:8080
    volumes:
      - ./wiremock/wwe-server:/home/wiremock
